### ISSUE TITLE
Table of current members

### ISSUE THREAD

**Issue by jmbrown864** [Team-Goatr/Makerspace-Automation-Suite#27]
![image](https://cloud.githubusercontent.com/assets/5743859/22129947/24663caa-de77-11e6-837f-665e3b971a0f.png)

**Comment by thomascoe** [comment]
To get this information, we should use PHP to query this G Suite API: https://developers.google.com/admin-sdk/directory/v1/guides/manage-users#get_all_domain_users

**Comment by thomascoe** [comment]
We have a "Subscription Expiration" date attribute for each user which can be used for the Next Payment Date column, but I don't think we have anywhere that stores "Member Since" info. Maybe we should re-evaluate if this info is necessary, and if it is then we need to add it to the user data schema in G Suite.

Maybe a more useful piece of information for the table is "Subscription Status" (i.e. pending, active, expired, cancelled)
