### ISSUE TITLE
Auto-populate fields on Admin Edit page

### ISSUE THREAD

**Issue by cmowenby** [Team-Goatr/Makerspace-Automation-Suite#43]

**Comment by thomascoe** [comment]
In admin-members-edit.html I already have some PHP code to get the user object from Google via my GSuiteAPI.php helper file. You just need to call methods on this object (ex: $user->getName()->getFullName();) in order to get the data to populate these fields.

Here is documentation of the JSON that should help you:
https://developers.google.com/admin-sdk/directory/v1/reference/users

The methods are auto-generated based on the JSON by prepending "get" and using camelcase (my example code above combined with the JSON in that link should help you understand how the method naming convention works)
