### ISSUE TITLE
Have API Keys Written to and Read From Files

### ISSUE THREAD

**Issue by cmowenby** [Team-Goatr/Makerspace-Automation-Suite#45]

**Comment by thomascoe** [comment]
Current API keys used on the server:
```
-rw-rw-r-- 1 ubuntu ubuntu 2336 Jan 27 22:39 /home/ubuntu/service_account.json
-rw-r--r-- 1 root   root     33 Feb  8 00:20 /home/ubuntu/stripe_public.txt
-rw-r--r-- 1 root   root     33 Feb  8 01:44 /home/ubuntu/stripe_secret.txt
```

**Comment by thomascoe** [comment]
service_account.json is the G Suite key. It is named that by default from Google. When you generate it, Google makes you download the .json file. 

Alternatively we could just have a file upload option for service_account.json instead of a text box. That may make sense considering the size of the key and the fact you have to download the .json file anyway.

The two stripe keys should just be small text boxes since you copy/paste those from the stripe website
