### ISSUE TITLE
G Suite SMTP Relay

### ISSUE THREAD

**Issue by ryanstrat** [Team-Goatr/Makerspace-Automation-Suite#68]
Send emails via G Suite SMTP servers.

**Comment by thomascoe** [comment]
http://www.pipiscrew.com/2015/04/php-send-mail-through-gmail-api/

**Comment by thomascoe** [comment]
Currently in the 'gmail' branch I have some work done towards this. If you visit the member edit page (by clicking the edit link on the admin view's member table), it attempts to send an email. This is the test I've been using for debugging.

I'm not sure what the issue is now, but I'm getting a 400 Bad Request. The error is thrown in the "try" block in the sendEmail function in GSuiteAPI.php. I think the '$service->users_messages->send()' call is throwing it, but I'm not sure why.

Can someone else please assist with debugging, I'm hitting a wall

**Comment by thomascoe** [comment]
Gmail API doc (not very useful because no PHP examples, but here it is): https://developers.google.com/gmail/api/guides/sending

**Comment by thomascoe** [comment]
What I'm specifically trying to do is send an email using PHP and service account credentials. Most of the stuff I've found online either doesn't use the service account (instead having users individually authorize), or isn't in PHP. 
The service account DOES have Domain-wide Delegation enabled, so it should be able to impersonate any valid user. I think the issue may be that I don't know how to make the service account impersonate a particular user to send email from that account.
